env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ["htmlacademy/es6", "plugin:react/recommended", "plugin:prettier/recommended"]

parser: "babel-eslint"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 9
  sourceType: module

plugins: ["react", "babel"]

settings:
  react:
    version: "17"

rules: {
    react/sort-comp: [2],
    quotes: ["error", "double"],
    object-curly-spacing: ["error", "always"],
    # indent:
    #   [
    #     "error",
    #     2,
    #     {
    #       SwitchCase: 1,
    #       VariableDeclarator: 1,
    #       MemberExpression: "off",
    #       FunctionDeclaration: { parameters: 2 },
    #       FunctionExpression: { parameters: 2 },
    #       CallExpression: { arguments: 1 },
    #     },
    #   ],
    no-console: "off",
    no-invalid-this: 0,
    babel/no-invalid-this: 1,
  }
